# Generated by Django 4.1.6 on 2023-02-07 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Realtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=50)),
                ("is_mvp", models.BooleanField(default=False)),
                (
                    "hire_date",
                    models.DateField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
