# Generated by Django 4.1.6 on 2023-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtors", "0002_realtor_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="photo",
            field=models.ImageField(blank=True, upload_to="photo_main/%Y/%m/%d/"),
        ),
    ]
