# Generated by Django 4.1.6 on 2023-02-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing", old_name="lsit_data", new_name="list_data",
        ),
    ]
