# Generated by Django 4.1.6 on 2023-02-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0002_rename_lsit_data_listing_list_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing", old_name="list_data", new_name="list_date",
        ),
    ]
